HIPPOPEOPLE/Controllers/AdministrationController.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using HIPPOPEOPLE.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace HIPPOPEOPLE.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        IContactRepository contactManagerRepo;
        IAttributeTypeRepository attributeTypeRepo;
        ICountryRepository countriesManagerRepo;
        IContactAttributeRepository contactAttributesRepo;


        #region CONSTRUCTORS
        public AdministrationController()
        {
            contactManagerRepo = new ContactManagerRepository(db);
            attributeTypeRepo = new AttributeTypeRepository(db);
            countriesManagerRepo = new CountryManagerRepository(db);
            contactAttributesRepo = new ContactAttributeManagerRepository(db);
        }
        public AdministrationController(ContactManagerRepository contactRepo, AttributeTypeRepository attributeRepo, CountryManagerRepository countryRepo, ContactAttributeManagerRepository contactAttributeRepo)
        {
            contactManagerRepo = contactRepo;
            attributeTypeRepo = attributeRepo;
            countriesManagerRepo = countryRepo;
            contactAttributesRepo = contactAttributeRepo;
        }
        public AdministrationController(IContactRepository contactRepo)
        {
            contactManagerRepo = contactRepo;
        }
        public AdministrationController(ICountryRepository countryRepo)
        {
            countriesManagerRepo = countryRepo;
        }
        public AdministrationController(IContactAttributeRepository contactAttrRepo)
        {
            contactAttributesRepo = contactAttrRepo;
        }
        public AdministrationController(IAttributeTypeRepository attribTypeRepo)
        {
            attributeTypeRepo = attribTypeRepo;
        }
        public AdministrationController(IContactRepository contactRepo, IContactAttributeRepository contactAttributeRepo)
        {
            contactManagerRepo = contactRepo;
            contactAttributesRepo = contactAttributeRepo;
        }

        public AdministrationController(IContactRepository contactRepo, ICountryRepository countryRepo)
        {
            contactManagerRepo = contactRepo;
            countriesManagerRepo = countryRepo;
        }

        public AdministrationController(AttributeTypeRepository attributeRepo)
        {
            attributeTypeRepo = attributeRepo;
        }

        public AdministrationController(ContactAttributeManagerRepository contactAttributeRepo)
        {
            contactAttributesRepo = contactAttributeRepo;
        }
        #endregion
        public ActionResult Index()
        {
            return View();
        }

        #region CONTACT
        public ActionResult Contact()
        {
            return View();
        }
        public ViewResult StronglyTypedContact()
        {
            return View(contactManagerRepo.Contacts.ToList());
        }

        public ViewResult StronglyTypedContactCards()
        {
            ContactCardViewModel mode = new ContactCardViewModel();
            mode.Contact = contactManagerRepo.Contacts.ToList();
            mode.ContactAtrribute = contactAttributesRepo.contactAttributes.ToList();
            return View(mode);
        }

        public ViewResult ContactTelerik()
        {
            return View(contactManagerRepo.Contacts.ToList());
        }

        public ViewResult ContactDataTable()
        {
            return View(contactManagerRepo.Contacts.ToList());
        }

        public ViewResult ContactAngularJs()
        {
            return View(contactManagerRepo.Contacts.ToList());
        }
        /// <summary>
        /// Action Result for Javascript
        /// </summary>
        /// <returns></returns>
        public ViewResult ContactJavascript()
        {
            NewPersonViewModel viewModel = new NewPersonViewModel();
            viewModel.Countries = countriesManagerRepo.Countries.ToList();
            return View(viewModel);
        }
        [Route("Administration/Contact/AssignContact/{contactId}")]
        public ViewResult AssignContact(int contactId)
        {
            AssignmentViewModel assignView = new AssignmentViewModel();
            assignView.AttributeTypes = attributeTypeRepo.AtrributeType.ToList();
            assignView.Contact = contactManagerRepo.Contacts.Where(c => c.Id == contactId).FirstOrDefault();
            assignView.ContactAtrributes = contactAttributesRepo.contactAttributes.Where(ca => ca.ContactId == contactId).ToList();
            return View(assignView);
        }      
        [HttpPost]
        public ActionResult AssignContacts(List<ContactAtrribute> ContactAtrribute)
        {
            ContactAtrribute.ForEach(c =>
            {
                if(contactAttributesRepo.contactAttributes.Any(caa => caa.AttributeId == c.AttributeId && caa.ContactId == c.ContactId) == false)
                {
                    var atType = contactAttributesRepo.Save(c);
                }                
            });

            return RedirectToAction("AssignContact", new { contactId = ContactAtrribute[0].ContactId});
        }
        /// <summary>
        /// Method to return A Contacts as JsonResults
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAContact(int contactId)
        {
            var data = contactManagerRepo.Contacts.Where(c => c.Id == contactId).FirstOrDefault();
            var serializedObject = JsonConvert.SerializeObject(data);
            return Json(serializedObject, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Method to return the list of Contacts as  JsonResults
        /// </summary>
        /// <returns></returns>
        public JsonResult GetContacts()
        {
            var data = contactManagerRepo.Contacts.ToList();
            var serializedObject = JsonConvert.SerializeObject(new { data = data});
            return Json(serializedObject, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetContactsNew()
        {
            //var data = contactManagerRepo.Contacts.ToList();
            var allData = contactManagerRepo.Contacts.ToList()
                .Select(ac => new PersonsModel
                {
                    Contact = ac,
                    ContactAtrribute = contactAttributesRepo.contactAttributes.Where(cc => cc.ContactId == ac.Id).ToList()
                });
            
            var serializedObject = JsonConvert.SerializeObject(new { data = allData });
            return Json(serializedObject, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GeTelerikContacts([DataSourceRequest] DataSourceRequest request, int? contactId)
        {
            var forKendo = new { total = contactManagerRepo.Contacts.Count(), data = contactManagerRepo.Contacts.ToDataSourceResult(request) };

            if (contactId.HasValue)
            {
                forKendo = new { total = contactManagerRepo.Contacts.Where(c => c.Id == contactId).Count(), data = contactManagerRepo.Contacts.Where(c => c.Id == contactId).ToDataSourceResult(request) };
            }
            
            var serializedObject = JsonConvert.SerializeObject(forKendo);
            return Json(serializedObject, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GeTelerikContactAttributes([DataSourceRequest] DataSourceRequest request, int contactId)
        {
            var forKendo = new { total = contactAttributesRepo.contactAttributes.Where(ca => ca.ContactId == contactId).Count(), data = contactAttributesRepo.contactAttributes.Where(ca => ca.ContactId == contactId).ToDataSourceResult(request) };
            var serializedObject = JsonConvert.SerializeObject(forKendo);
            return Json(serializedObject, JsonRequestBehavior.AllowGet);
        }
        [Route("Administration/StronglyTypedContact/NewPerson")]
        public ActionResult NewPerson()
        {
            NewPersonViewModel viewModel = new NewPersonViewModel();
            viewModel.Countries = countriesManagerRepo.Countries.ToList();
            return View(viewModel);
        }

        public ActionResult AddAContact(NewPersonViewModel personViewModel)
        {
            var contact = contactManagerRepo.Save(personViewModel.Contact);

            if (contact != null)
            {
                return RedirectToAction("StronglyTypedContact");
            }
            return View();
        }

        [Route("Administration/StronglyTypedContact/EditPerson/{contactId}")]
        public ActionResult EditPerson(int contactId)
        {
            NewPersonViewModel viewModel = new NewPersonViewModel();
            viewModel.Countries = countriesManagerRepo.Countries.ToList();
            viewModel.Contact = contactManagerRepo.Contacts.Where(c => c.Id == contactId).FirstOrDefault();
            return View(viewModel);
        }

        [Route("Administration/StronglyTypedContact/EditPerson")]
        [HttpPost]
        public ActionResult EditPerson(NewPersonViewModel personViewModel)
        {
            var contact = contactManagerRepo.Save(personViewModel.Contact);

            if (contact != null)
            {
                return RedirectToAction("StronglyTypedContact");
            }

            return View(personViewModel);
        }

        [Route("Administration/StronglyTypedContact/DeletePerson/{contactId}")]
        public ActionResult DeletePerson(int contactId)
        {
            var contacToRemove = contactManagerRepo.Contacts.Where(c => c.Id == contactId).FirstOrDefault();
            contactManagerRepo.Delete(contacToRemove);
            return RedirectToAction("StronglyTypedContact");
        }
        #endregion

        #region ATTRIBUTETYPE
        public ActionResult AttributeTypes()
        {

HIPPOPEOPLE/Views/Shared/_Footer.cshtml
<footer class="footer">
    <span class="pull-right">
        Aghogho Bernard
    </span>
    HIPPO PEOPLE @DateTime.Now.Date.Year
</footer>

HIPPOPEOPLE/Views/Shared/_Header.cshtml
<div class="color-line">
</div>
<div id="logo" class="light-version">
    <span>
        HIPPO PERSONS
    </span>
</div>
<nav role="navigation">
    <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
    <div class="small-logo">
        <span class="text-primary">HIPPOPEOPLE APP</span>
    </div>
    <form role="search" class="navbar-form-custom" method="post" action="#">
        <div class="form-group">
            <input type="text" placeholder="Search something special" class="form-control" name="search">
        </div>
    </form>
    <div class="mobile-menu">
        <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
            <i class="fa fa-chevron-down"></i>
        </button>
        <div class="collapse mobile-navbar" id="mobile-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a class="" href="@Url.Action("Login", "CommonViews")">Login</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Register", "CommonViews")">Logout</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("ProfilePage", "AppViews")">Profile</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="navbar-right">
        <ul class="nav navbar-nav no-borders">
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-keypad"></i>
                </a>
                <div class="dropdown-menu hdropdown bigmenu animated flipInX">
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <a href="@Url.Action("StronglyTypedContact", "Administration")">
                                        <i class="pe pe-7s-users text-info"></i>
                                        <h5>Persons MVC</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("ContactDataTable", "Administration")">
                                        <i class="pe pe-7s-users text-warning"></i>
                                        <h5>Persons Datatables</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("ContactTelerik", "Administration")">
                                        <i class="pe pe-7s-users text-success"></i>
                                        <h5>Persons Telerik</h5>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <a href="@Url.Action("StronglyTypedContactCards", "Administration")">
                                        <i class="pe pe-7s-box1 text-info"></i>
                                        <h5>Person Cards</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("ContactAngularJs", "Administration")">
                                        <i class="pe pe-7s-users text-danger"></i>
                                        <h5>Person Angular</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("AttributeTypes", "Administration")">
                                        <i class="pe pe-7s-tools text-success"></i>
                                        <h5>Attribute Type</h5>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </li>
            <li class="dropdown">
                <a href="#" onclick="$('#hippoLogoutForm').submit();">
                    <i class="pe-7s-upload pe-rotate-90"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

HIPPOPEOPLE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>HIPPOPEOPLE | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Primary vendor style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
                                              
    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="@Html.PageClass() @ViewBag.ExtraClasses">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            <img src="~/Content/img/ui-topfm.png" alt="HIPPOPEOPLE" />
            <h1>HIPPOPEOPLE - DEMO</h1>
            <p>Contact Manager by Aghogho Bernard. </p>
            <div class="spinner">
                <div class="rect1">
                </div>
                <div class="rect2">
                </div>
                <div class="rect3">
                </div>
                <div class="rect4">
                </div>
                <div class="rect5">
                </div>
            </div>
        </div>
    </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header -->
    <div id="header">
        @Html.Partial("_Header")
    </div>

    <!-- Navigation -->
    <aside id="menu">
        @Html.Partial("_Navigation")
    </aside>

    <!-- Main view  -->
    <div id="wrapper">
        @RenderBody()

        <!-- Footer-->
        @Html.Partial("_Footer")
    </div>

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

    @if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "hippoLogoutForm" }))
        {
            @Html.AntiForgeryToken()
        }
    }


</body>
</html>

HIPPOPEOPLE/Views/Shared/_Layout_Blank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>HIPPOPEOPLE | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="blank">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            <img src="~/Content/img/ui-topfm.png" alt="HIPPOPEOPLE" />
            <h1>HIPPOPEOPLE - SMS</h1>
            <p>Sales Management tool by Infini Tech. </p>
            <div class="spinner"> 
                <div class="rect1">
                </div>
                <div class="rect2">
                </div> 
                <div class="rect3">
                </div> 
                <div class="rect4">
                </div>
                <div class="rect5">
                </div> 
            </div> 
        </div> 
    </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="color-line"></div>

    <div class="back-link">
        <a href="/" target="_blank" class="btn btn-primary"><i class="fa fa-home"></i>&nbsp;HIPPOPEOPLE Home</a>
    </div>

    <!-- Main view  -->
    @RenderBody()

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

</body>
</html>

HIPPOPEOPLE/Views/Shared/_Layout_Boxed.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>HIPPOPEOPLE | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Primary vendor style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
                                              
    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="@Html.PageClass()">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            <img src="~/Content/img/ui-topfm.png" alt="HIPPOPEOPLE" />
            <h1>HIPPOPEOPLE - SMS</h1>
            <p>Sales Management tool by Infini Tech. </p>
            <div class="spinner">
                <div class="rect1">
                </div>
                <div class="rect2">
                </div>
                <div class="rect3">
                </div>
                <div class="rect4">
                </div>
                <div class="rect5">
                </div>
            </div>
        </div>
    </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="boxed-wrapper">

        <!-- Header -->
        <div id="header">
            @Html.Partial("_Header")
        </div>

        <!-- Navigation -->
        <aside id="menu">
            @Html.Partial("_Navigation")
        </aside>

        <!-- Main view  -->
        <div id="wrapper">
            @RenderBody()

            <!-- Footer-->
            @Html.Partial("_Footer")
        </div>

    </div>

        <!-- Section for main scripts render -->
        @Scripts.Render("~/bundles/jquery/js")
        @Scripts.Render("~/bundles/bootstrap/js")
        @Scripts.Render("~/bundles/homer/js")

        <!-- Handler for local scripts -->
        @RenderSection("scripts", required: false)
</body>
</html>

HIPPOPEOPLE/Views/Shared/_Layout_Hippo_Blank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>HIPPOPEOPLE | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="blank">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            <img src="~/Content/img/ui-topfm.png" alt="HIPPOPEOPLE" />
            <h1>HIPPOPEOPLE - SMS</h1>
            <p>Sales Management tool by Infini Tech. </p>
            <div class="spinner"> 
                <div class="rect1">
                </div>
                <div class="rect2">
                </div> 
                <div class="rect3">
                </div> 
                <div class="rect4">
                </div>
                <div class="rect5">
                </div> 
            </div> 
        </div> 
    </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="color-line"></div>

    <div class="back-link">
        <a href="@Url.Action("Login","Account")" target="_blank" class="btn btn-primary"><i class="fa fa-home"></i>&nbsp;ENTER DEMO</a>
    </div>
    <br /><br />

    <!-- Main view  -->
    @RenderBody()

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

</body>
</html>

HIPPOPEOPLE/Views/Shared/_Layout_Landing.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>HOMER | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="landing-page">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            <img src="~/Content/img/ui-topfm.png" alt="HIPPOPEOPLE" />
            <h1>HIPPOPEOPLE - SMS</h1>
            <p>Sales Management tool by Infini Tech. </p>
            <div class="spinner">
                <div class="rect1">
                </div>
                <div class="rect2">
                </div>
                <div class="rect3">
                </div>
                <div class="rect4">
                </div>
                <div class="rect5">
                </div>
            </div>
        </div>
    </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- Main view  -->
    @RenderBody()

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>